<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'add_user' => [[], ['_controller' => 'App\\Controller\\userController::adduser'], [], [['text', '/api/register']], [], [], []],
    'get_one_user' => [['id'], ['_controller' => 'App\\Controller\\userController::getOneuser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/get']], [], [], []],
    'get_all_users' => [[], ['_controller' => 'App\\Controller\\userController::getAllusers'], [], [['text', '/api/get-all']], [], [], []],
    'update_user' => [['id'], ['_controller' => 'App\\Controller\\userController::updateuser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/update']], [], [], []],
    'delete_user' => [['id'], ['_controller' => 'App\\Controller\\userController::deleteuser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/delete']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
];
