<?php

namespace ContainerA7D8ByM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4x8YnIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._4x8YnI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._4x8YnI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\cartController::addProductToCart' => ['privates', '.service_locator._ce7ysY', 'get_ServiceLocator_Ce7ysYService', true],
            'App\\Controller\\cartController::deleteProductFromCart' => ['privates', '.service_locator._ce7ysY', 'get_ServiceLocator_Ce7ysYService', true],
            'App\\Controller\\cartController::getOneCart' => ['privates', '.service_locator._ce7ysY', 'get_ServiceLocator_Ce7ysYService', true],
            'App\\Controller\\cartController::validateCart' => ['privates', '.service_locator._ce7ysY', 'get_ServiceLocator_Ce7ysYService', true],
            'App\\Controller\\orderController::deleteProductFromorder' => ['privates', '.service_locator._ce7ysY', 'get_ServiceLocator_Ce7ysYService', true],
            'App\\Controller\\orderController::formatOrder' => ['privates', '.service_locator.H0QGoQM', 'get_ServiceLocator_H0QGoQMService', true],
            'App\\Controller\\orderController::getAllorders' => ['privates', '.service_locator._ce7ysY', 'get_ServiceLocator_Ce7ysYService', true],
            'App\\Controller\\orderController::getOneorder' => ['privates', '.service_locator._ce7ysY', 'get_ServiceLocator_Ce7ysYService', true],
            'App\\Controller\\productController::addProduct' => ['privates', '.service_locator._ce7ysY', 'get_ServiceLocator_Ce7ysYService', true],
            'App\\Controller\\productController::deleteproduct' => ['privates', '.service_locator._ce7ysY', 'get_ServiceLocator_Ce7ysYService', true],
            'App\\Controller\\productController::getAllproducts' => ['privates', '.service_locator._ce7ysY', 'get_ServiceLocator_Ce7ysYService', true],
            'App\\Controller\\productController::getOneProduct' => ['privates', '.service_locator._ce7ysY', 'get_ServiceLocator_Ce7ysYService', true],
            'App\\Controller\\productController::updateproduct' => ['privates', '.service_locator._ce7ysY', 'get_ServiceLocator_Ce7ysYService', true],
            'App\\Controller\\userController::getOneuser' => ['privates', '.service_locator._ce7ysY', 'get_ServiceLocator_Ce7ysYService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\cartController:addProductToCart' => ['privates', '.service_locator._ce7ysY', 'get_ServiceLocator_Ce7ysYService', true],
            'App\\Controller\\cartController:deleteProductFromCart' => ['privates', '.service_locator._ce7ysY', 'get_ServiceLocator_Ce7ysYService', true],
            'App\\Controller\\cartController:getOneCart' => ['privates', '.service_locator._ce7ysY', 'get_ServiceLocator_Ce7ysYService', true],
            'App\\Controller\\cartController:validateCart' => ['privates', '.service_locator._ce7ysY', 'get_ServiceLocator_Ce7ysYService', true],
            'App\\Controller\\orderController:deleteProductFromorder' => ['privates', '.service_locator._ce7ysY', 'get_ServiceLocator_Ce7ysYService', true],
            'App\\Controller\\orderController:formatOrder' => ['privates', '.service_locator.H0QGoQM', 'get_ServiceLocator_H0QGoQMService', true],
            'App\\Controller\\orderController:getAllorders' => ['privates', '.service_locator._ce7ysY', 'get_ServiceLocator_Ce7ysYService', true],
            'App\\Controller\\orderController:getOneorder' => ['privates', '.service_locator._ce7ysY', 'get_ServiceLocator_Ce7ysYService', true],
            'App\\Controller\\productController:addProduct' => ['privates', '.service_locator._ce7ysY', 'get_ServiceLocator_Ce7ysYService', true],
            'App\\Controller\\productController:deleteproduct' => ['privates', '.service_locator._ce7ysY', 'get_ServiceLocator_Ce7ysYService', true],
            'App\\Controller\\productController:getAllproducts' => ['privates', '.service_locator._ce7ysY', 'get_ServiceLocator_Ce7ysYService', true],
            'App\\Controller\\productController:getOneProduct' => ['privates', '.service_locator._ce7ysY', 'get_ServiceLocator_Ce7ysYService', true],
            'App\\Controller\\productController:updateproduct' => ['privates', '.service_locator._ce7ysY', 'get_ServiceLocator_Ce7ysYService', true],
            'App\\Controller\\userController:getOneuser' => ['privates', '.service_locator._ce7ysY', 'get_ServiceLocator_Ce7ysYService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\cartController::addProductToCart' => '?',
            'App\\Controller\\cartController::deleteProductFromCart' => '?',
            'App\\Controller\\cartController::getOneCart' => '?',
            'App\\Controller\\cartController::validateCart' => '?',
            'App\\Controller\\orderController::deleteProductFromorder' => '?',
            'App\\Controller\\orderController::formatOrder' => '?',
            'App\\Controller\\orderController::getAllorders' => '?',
            'App\\Controller\\orderController::getOneorder' => '?',
            'App\\Controller\\productController::addProduct' => '?',
            'App\\Controller\\productController::deleteproduct' => '?',
            'App\\Controller\\productController::getAllproducts' => '?',
            'App\\Controller\\productController::getOneProduct' => '?',
            'App\\Controller\\productController::updateproduct' => '?',
            'App\\Controller\\userController::getOneuser' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\cartController:addProductToCart' => '?',
            'App\\Controller\\cartController:deleteProductFromCart' => '?',
            'App\\Controller\\cartController:getOneCart' => '?',
            'App\\Controller\\cartController:validateCart' => '?',
            'App\\Controller\\orderController:deleteProductFromorder' => '?',
            'App\\Controller\\orderController:formatOrder' => '?',
            'App\\Controller\\orderController:getAllorders' => '?',
            'App\\Controller\\orderController:getOneorder' => '?',
            'App\\Controller\\productController:addProduct' => '?',
            'App\\Controller\\productController:deleteproduct' => '?',
            'App\\Controller\\productController:getAllproducts' => '?',
            'App\\Controller\\productController:getOneProduct' => '?',
            'App\\Controller\\productController:updateproduct' => '?',
            'App\\Controller\\userController:getOneuser' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
