<?php

namespace ContainerA7D8ByM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ce7ysYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._ce7ysY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._ce7ysY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'tokenService' => ['services', 'App\\utils\\tokenVerification', 'getTokenVerificationService', true],
        ], [
            'tokenService' => 'App\\utils\\tokenVerification',
        ]);
    }
}
