<?php

namespace ContainerA7D8ByM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\orderController' shared autowired service.
     *
     * @return \App\Controller\orderController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/orderController.php';

        $container->services['App\\Controller\\orderController'] = $instance = new \App\Controller\orderController(($container->services['App\\Repository\\ProductRepository'] ?? $container->load('getProductRepositoryService')), ($container->services['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->services['App\\Repository\\OrderRepository'] ?? $container->load('getOrderRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('App\\Controller\\orderController', $container));

        return $instance;
    }
}
